### ISSUE TITLE
Incompatible with No UltraViolence mod; current map closes upon trying to fire at enemies about 75% of the time

### ISSUE THREAD

**Issue by Star-X555** [mmaulwurff/typist.pk3#104]
Specifically, this mod:
https://www.moddb.com/mods/no-ultra-violence

For whatever reason, upon shooting enemies, about 75% of the time the current map closes and this is in the log:

> VM execution aborted: tried to read from address zero.
> Called from Actor.CountInv at gzdoom.pk3:zscript/actors/inventory_util.zs
> Called from tt_EnemySpeedController.isSlowedDown at typist-v0.7.2.pk3:zscript/typist/world_changer/tt_enemy_speed_controller.zs, line 59
> Called from tt_EnemySpeedController.changeWorld at typist-v0.7.2.pk3:zscript/typist/world_changer/tt_enemy_speed_controller.zs, line 47
> Called from tt_WorldChangers.changeWorld at typist-v0.7.2.pk3:zscript/typist/world_changer/tt_world_changers.zs, line 45
> Called from tt_PlayerSupervisor.Tick at typist-v0.7.2.pk3:zscript/typist/player_handler/tt_player_supervisor.zs, line 168
> Called from tt_EventHandler.WorldTick at typist-v0.7.2.pk3:zscript/typist/event_handler/tt_event_handler.zs, line 29

I tested without No Ultraviolence and it seems to work fine, which means SOMETHING in NoUV is breaking Typist.

I'd love a fix, as the idea of a "Doom Teaches Typing" game is something pretty neat, but I'd prefer if NoUV can be used simultaneously with Typist.  Till then, I guess I'll try Chex Quest and see how that goes.

**Comment by mmaulwurff** [comment]
Fresh build can be downloaded here: https://github.com/mmaulwurff/typist.pk3/archive/refs/heads/master.zip
