### ISSUE TITLE
Allow capital letters in custom lessons

### ISSUE THREAD

**Issue by paulfioravanti** [mmaulwurff/typist.pk3#107]
When reading in word lists for custom lessons, it seems that all words get lowercased.

https://github.com/mmaulwurff/typist.pk3/blob/b38f5aa5262308e81c48a50d36c780310e671041/zscript/typist/lesson/custom_lesson.zs#L65-L67

For word lists that contain person or place names etc, it would great to be able to keep the original word case containing capital letters, perhaps in a config option(?), rather than have convert-to-lower be the default.

**Comment by paulfioravanti** [comment]
In case anyone else sees this, for reference, I made this change in my fork [here](https://github.com/paulfioravanti/typist.pk3/commit/8b1b442bf69eabf7d5eb762cde697e2d56f39586).

**Comment by paulfioravanti** [comment]
@mmaulwurff was there a specific reason you can recall that necessitated downcasing all letters in custom word lists/lessons?

**Comment by mmaulwurff** [comment]
I don't remember why I did this. Possible reasons:
- lesson difficulty: for faster typing.
- performance: for shorter word lists.

**Comment by paulfioravanti** [comment]
Would you consider either:

- loosening the behavior so that there's no unexpected limitations on custom lessons (I say unexpected because I had to go look at the code to see why my word lists weren't being displayed as-is)?
- allowing parameters like whether capital letters can be used or not, and min/max word length, to be configurable in the Typist UI menus?

If you think that these suggestions aren't appropriate for your project, that's okay! I'd be happy to just continue tweaking my fork where I can :)

**Comment by mmaulwurff** [comment]
I think removing all the limitations is the best idea. Letter case, allowed characters, word length - let it be decided by the text itself.

Now I remember - the idea behind custom lesson was to allow the user throw any text at Typist and it would just work. That idea proved to be not feasible, as some preparation and manual filtering was always needed.

**Comment by paulfioravanti** [comment]
So, if I understand your comment, you'd be in favor of getting rid of the `filterLetters(contents)` and `filterWords(words, result._wordSet)` functions altogether, but that wasn't possible due to some filtering always being needed. In that case, would you support at least loosening the filters in some ways, like allowing capital letters and/or allowing short(er)/long(er) words? Or, are those conditions the ones that you mentioned you always needed?

If those specific filters need to be there for some reason, then I respect that, and I'm happy to close this issue. I'm planning to keep the altered conditions in my fork, though, but are there any landmines I should watch out for by keeping them in?

**Comment by mmaulwurff** [comment]
I may have not expressed myself clearly. I'd be in favor of getting rid of filter functions altogether, and I see no disadvantages of that.

Initially, I wanted to accept all kinds of text - like, full stories. Hence the filters - to extract words from the text. But then I found out that the best way to use custom lessons is with simple word lists.
